/**
 * SprintPulse - Executive Stakeholder Report Generator
 * Generates formatted Markdown and printable HTML executive briefs for leadership
 */

const SprintExportReport = {
  /**
   * Generates a structured Markdown report
   */
  generateMarkdown(squad, sprint, kpis, risks, retroCards) {
    const today = new Date().toISOString().split('T')[0];
    
    return `# 📊 Sprint Executive Delivery Briefing

**Project / Squad:** ${squad.name} (${squad.domain})  
**Active Sprint:** ${sprint.name}  
**Sprint Window:** ${sprint.startDate} to ${sprint.endDate} (Day ${sprint.currentDay} of ${sprint.totalDays})  
**Report Generated By:** Associate IT Project Manager  
**Date:** ${today}  

---

## 🎯 1. Executive Summary & Sprint Health

- **Overall Sprint Health Index:** **${kpis.healthScore.value}/100** (${kpis.healthScore.status})
- **Sprint Commitment:** **${kpis.committed} Story Points (SP)**
- **Completed Velocity:** **${kpis.completed} SP** (${kpis.predictability}% Predictability Ratio)
- **Scope Volatility / Creep:** **${kpis.scopeCreepIndex}%** (+${kpis.addedMidSprint} SP injected mid-sprint)
- **Code Review Bottleneck Level:** **${kpis.overdueReviewCount} PRs >48h** (Avg Review Time: ${kpis.avgReviewHours}h)

> **Sprint Goal:** "${sprint.goal}"

---

## ⚠️ 2. Key Delivery Risks & Blocker Radar

${risks.map(r => `- **[${r.type.toUpperCase()}] ${r.title}:** ${r.desc}\n  *Recommended PM Action:* ${r.recommendation}`).join('\n\n')}

---

## 👥 3. Team Workload & Capacity Allocation

| Team Member | Role | Capacity (SP) | Assigned (SP) | Allocation Status |
| :--- | :--- | :---: | :---: | :--- |
${sprint.workload.map(w => {
  const status = w.assignedSP > w.capacitySP ? '⚠️ Overloaded' : '✅ Balanced';
  return `| ${w.name} | ${w.role} | ${w.capacitySP} SP | ${w.assignedSP} SP | ${status} |`;
}).join('\n')}

---

## 🔄 4. Retrospective Action Items for Next Sprint

${retroCards.filter(c => c.category === 'action-items').map(c => `- **[${c.assignee || 'Team'}]** ${c.text} (👍 ${c.votes} votes)`).join('\n')}

---
*Report automatically generated via **SprintPulse Agile Analytics Platform**.*
`;
  },

  /**
   * Renders the executive report preview in the UI
   */
  renderReportView() {
    const activeSquad = SPRINT_PULSE_DATA.squads[SPRINT_PULSE_DATA.activeSquadId];
    const activeSprint = activeSquad.sprints[SPRINT_PULSE_DATA.activeSprintId];
    const kpis = SprintMetrics.calculateSprintKPIs(activeSprint);
    const risks = SprintRiskEngine.evaluateSprintRisks(activeSprint);
    const retroCards = SprintRetrospective.getCards();

    const mdContent = this.generateMarkdown(activeSquad, activeSprint, kpis, risks, retroCards);
    const previewContainer = document.getElementById('executive-report-content');
    if (previewContainer) {
      previewContainer.innerHTML = `
        <div class="report-paper">
          <div class="report-header">
            <div>
              <span class="brand-tag">Executive Delivery Briefing</span>
              <h1 style="font-size: 1.6rem; margin-top: 0.25rem;">${activeSprint.name}</h1>
              <div style="font-size: 0.85rem; color: var(--text-muted); margin-top: 0.25rem;">
                ${activeSquad.name} &bull; ${activeSquad.domain}
              </div>
            </div>
            <div style="text-align: right;">
              <div class="kpi-value" style="color: var(--primary); font-size: 2.2rem;">${kpis.healthScore.value}<span style="font-size: 1rem; color: var(--text-muted);">/100</span></div>
              <div class="kpi-badge badge-positive" style="font-size: 0.8rem;">${kpis.healthScore.status}</div>
            </div>
          </div>

          <div style="background: var(--bg-input); border-radius: var(--radius-md); padding: 1rem; margin-bottom: 1.5rem; border-left: 4px solid var(--primary);">
            <strong style="color: var(--primary);">Sprint Goal:</strong> <em>"${activeSprint.goal}"</em>
          </div>

          <div class="report-grid-2col">
            <div class="card" style="padding: 1.25rem;">
              <h3 style="font-size: 0.95rem; margin-bottom: 0.75rem;">📈 Delivery Velocity KPIs</h3>
              <ul style="list-style: none; display: flex; flex-direction: column; gap: 0.5rem; font-size: 0.85rem;">
                <li style="display: flex; justify-content: space-between;">
                  <span style="color: var(--text-muted);">Committed vs Done:</span>
                  <strong>${kpis.completed} / ${kpis.committed} SP</strong>
                </li>
                <li style="display: flex; justify-content: space-between;">
                  <span style="color: var(--text-muted);">Predictability Ratio:</span>
                  <strong style="color: var(--status-on-track);">${kpis.predictability}%</strong>
                </li>
                <li style="display: flex; justify-content: space-between;">
                  <span style="color: var(--text-muted);">Scope Creep Index:</span>
                  <strong style="color: ${kpis.scopeCreepIndex > 10 ? 'var(--status-critical)' : 'var(--text-primary)'};">+${kpis.scopeCreepIndex}%</strong>
                </li>
                <li style="display: flex; justify-content: space-between;">
                  <span style="color: var(--text-muted);">Avg PR Review Turnaround:</span>
                  <strong>${kpis.avgReviewHours} Hours</strong>
                </li>
              </ul>
            </div>

            <div class="card" style="padding: 1.25rem;">
              <h3 style="font-size: 0.95rem; margin-bottom: 0.75rem;">🛡️ Delivery Risk Summary</h3>
              <div style="display: flex; flex-direction: column; gap: 0.5rem; font-size: 0.8rem;">
                ${risks.map(r => `
                  <div style="padding: 0.5rem; background: var(--bg-input); border-radius: var(--radius-sm); border-left: 3px solid ${r.type === 'critical' ? 'var(--status-critical)' : r.type === 'warning' ? 'var(--status-warning)' : 'var(--status-info)'};">
                    <strong>${r.title}</strong>: ${r.desc}
                  </div>
                `).join('')}
              </div>
            </div>
          </div>

          <div style="margin-top: 1.5rem;">
            <h3 style="font-size: 1rem; margin-bottom: 0.75rem;">👥 Team Capacity & Allocation</h3>
            <table style="width: 100%; border-collapse: collapse; font-size: 0.82rem;">
              <thead>
                <tr style="background: var(--bg-input); text-align: left;">
                  <th style="padding: 0.6rem;">Member</th>
                  <th style="padding: 0.6rem;">Role</th>
                  <th style="padding: 0.6rem;">Capacity</th>
                  <th style="padding: 0.6rem;">Assigned</th>
                  <th style="padding: 0.6rem;">Status</th>
                </tr>
              </thead>
              <tbody>
                ${activeSprint.workload.map(w => `
                  <tr style="border-bottom: 1px solid var(--border-subtle);">
                    <td style="padding: 0.6rem; font-weight: 600;">${w.name}</td>
                    <td style="padding: 0.6rem; color: var(--text-muted);">${w.role}</td>
                    <td style="padding: 0.6rem;">${w.capacitySP} SP</td>
                    <td style="padding: 0.6rem;">${w.assignedSP} SP</td>
                    <td style="padding: 0.6rem;">
                      <span class="kpi-badge ${w.assignedSP > w.capacitySP ? 'badge-warning' : 'badge-positive'}">
                        ${w.assignedSP > w.capacitySP ? 'Overloaded' : 'Balanced'}
                      </span>
                    </td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>

          <div style="margin-top: 2rem; display: flex; justify-content: flex-end; gap: 1rem;">
            <button class="btn btn-outline" onclick="SprintExportReport.copyMarkdown()">
              📋 Copy Markdown Briefing
            </button>
            <button class="btn btn-primary" onclick="window.print()">
              🖨️ Print / Save as PDF
            </button>
          </div>
        </div>
      `;
    }
  },

  copyMarkdown() {
    const activeSquad = SPRINT_PULSE_DATA.squads[SPRINT_PULSE_DATA.activeSquadId];
    const activeSprint = activeSquad.sprints[SPRINT_PULSE_DATA.activeSprintId];
    const kpis = SprintMetrics.calculateSprintKPIs(activeSprint);
    const risks = SprintRiskEngine.evaluateSprintRisks(activeSprint);
    const retroCards = SprintRetrospective.getCards();

    const md = this.generateMarkdown(activeSquad, activeSprint, kpis, risks, retroCards);
    navigator.clipboard.writeText(md).then(() => {
      App.showToast('Executive Report copied to clipboard in Markdown format!', 'success');
    }).catch(err => {
      App.showToast('Failed to copy to clipboard', 'error');
    });
  }
};
